support window build

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -36,8 +36,9 @@ jobs:
       - name: Install xgo (for go musl c-archive)
         run: |
           go install github.com/crazy-max/xgo@latest
-          echo "export PATH=\"$HOME/go/bin:$PATH\"" >> $GITHUB_ENV
-          echo "[debug] xgo version: $($HOME/go/bin/xgo --version || echo not found)"
+          export PATH="$HOME/go/bin:$PATH"
+          echo "$HOME/go/bin" >> $GITHUB_PATH
+          echo "[debug] xgo version: $(xgo --help | head -n 1 || echo not found)"
       - name: Build plugin_lossy_ddl go c-archive (xgo musl)
         run: |
           cd plugins/plugin_lossy_ddl/go
